### ISSUE TITLE
Cannot import name 'postprocess_model_xml' from 'robosuite.utils.mjcf_utils'

### ISSUE THREAD

**Issue by AndingDrLin** [j96w/MimicPlay#15]
When I prepare for the dataset, I ran this command
```
python scripts/dataset_states_to_obs.py --dataset 'datasets/playdata/demo_modified.hdf5' --done_mode 0 --camera_names agentview robot0_eye_in_hand --camera_height 84 --camera_width 84 --output_name image_demo_local.hdf5 --exclude-next-obs
```
but I have the problem with an import error of robosuite. Here is the output of the terminal:
```
[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /home/glasgow-auto/Project/MimicPlay/robosuite/robosuite/scripts/setup_macros.py (macros.py:55)
Traceback (most recent call last):
  File "scripts/dataset_states_to_obs.py", line 346, in <module>
    dataset_states_to_obs(args)
  File "scripts/dataset_states_to_obs.py", line 151, in dataset_states_to_obs
    env = EnvUtils.create_env_for_data_processing(
  File "/home/glasgow-auto/anaconda3/envs/mimicplay/lib/python3.8/site-packages/robomimic/utils/env_utils.py", line 225, in create_env_for_data_processing
    env_class = get_env_class(env_type=env_type)
  File "/home/glasgow-auto/anaconda3/envs/mimicplay/lib/python3.8/site-packages/robomimic/utils/env_utils.py", line 35, in get_env_class
    from robomimic.envs.env_robosuite import EnvRobosuite
  File "/home/glasgow-auto/anaconda3/envs/mimicplay/lib/python3.8/site-packages/robomimic/envs/env_robosuite.py", line 12, in <module>
    from robosuite.utils.mjcf_utils import postprocess_model_xml
ImportError: cannot import name 'postprocess_model_xml' from 'robosuite.utils.mjcf_utils' (/home/glasgow-auto/Project/MimicPlay/robosuite/robosuite/utils/mjcf_utils.py)
```
It seems that robosuite (v1.4.1_libero) does not have this attribute. How can I solve this problem?

**Comment by carloskiyoto** [comment]
I got the same problem

**Comment by Ashlot2002** [comment]
I got the same problemQAQ
